/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtocolModule"
 * 	found in "C:/devel/BlackBoxTT/bbproto/bbproto.asn1"
 * 	`asn1c -gen-PER -S`
 */

#ifndef	_BBHwndMsg_H_
#define	_BBHwndMsg_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BBHwndMsg */
typedef struct BBHwndMsg {
	long	 hwnd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BBHwndMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BBHwndMsg;

#ifdef __cplusplus
}
#endif

#endif	/* _BBHwndMsg_H_ */
#include <asn_internal.h>
