/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtocolModule"
 * 	found in "C:/devel/BlackBoxTT/bbproto/bbproto.asn1"
 * 	`asn1c -gen-PER -S`
 */

#ifndef	_Command_H_
#define	_Command_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BBHwndMsg.h"
#include "BB32WMMsg.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Command_PR {
	Command_PR_NOTHING,	/* No components present */
	Command_PR_bbhwnd,
	Command_PR_bb32wm
} Command_PR;

/* Command */
typedef struct Command {
	Command_PR present;
	union Command_u {
		BBHwndMsg_t	 bbhwnd;
		BB32WMMsg_t	 bb32wm;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Command_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Command;

#ifdef __cplusplus
}
#endif

#endif	/* _Command_H_ */
#include <asn_internal.h>
