/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef BBPAGER_PRIVATE_H
#define BBPAGER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"4.0.0.94"
#define VER_MAJOR	4
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	94
#define COMPANY_NAME	"TheDevTeam"
#define FILE_VERSION	"bb4win_mod - bbPager"
#define FILE_DESCRIPTION	"window manager plugin for Blackbox for Windows"
#define INTERNAL_NAME	"bbPager"
#define LEGAL_COPYRIGHT	"© 2003-2008 nc-17|TheDevTeam"
#define LEGAL_TRADEMARKS	"none"
#define ORIGINAL_FILENAME	"bbPager.dll"
#define PRODUCT_NAME	"bb4win_mod - bbPager"
#define PRODUCT_VERSION	"bb4win_mod"

#endif /*BBPAGER_PRIVATE_H*/
