# --------------------------------------------------------------------
# makefile for bbPager - gcc mingw

TOP = ../..

BIN    = bbPager.dll
OBJ    = bbPager.obj Drawing.obj Settings.obj bbPager_private.res
INSTALL_IF_NEW = $(BIN) bbPager.html

include $(TOP)/build/makefile.inc
